# Generated by Django 4.2.14 on 2024-08-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_caja_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='caja_texto',
            new_name='hoja_vida',
        ),
    ]
