# Generated by Django 4.2.14 on 2024-08-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_rename_caja_texto_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre completo'),
        ),
    ]
